defaults:
  - cleaning: default # configs/cleaning/default.yaml
  - datamodule: default # configs/datamodule/default.yaml
  - model: bert_reg # configs/model/bert_reg.yaml
  - optimizer: adamw # -configs/optimizer/adamw.yaml

  - callback_early_stop: early_stop
  - callback_lr_monitor: lr_monitor
  - logger: mlflow

  - _self_

seed: 42 # Lightning + numpy + torch seed

trainer:
  accelerator: gpu # "cpu", "mps" or "gpu"
  devices: 1
  max_epochs: 5
  precision: 16
  log_every_n_steps: 20
  num_sanity_val_steps: 2
  deterministic: true

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S} # where checkpoints & .hydra go
  sweep:
    dir: multiruns/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    env_set:
      TOKENIZERS_PARALLELISM: "false"
