_target_: ielts_band_predictor.data.IELTSDataModule

raw_path: data/raw/essays.jsonl
batch_size: 16
max_length: 512
val_size: 0.1
num_workers: 4
seed: ${seed}

tokenizer_name: ${model.pretrained_name}
max_non_ascii_ratio: ${cleaning.max_non_ascii_ratio}
max_non_ascii_abs: ${cleaning.max_non_ascii_abs}
